
import React, { useState } from 'react';
import { BookOpen, Cpu, Shield, Zap, Wifi, Activity, Server, Clock, GitMerge, FileCode, CheckCircle2, ArrowRight, Microchip, Layers, Lock } from 'lucide-react';

const INSIGHTS = [
    {
        id: 'cpc',
        category: 'Architecture',
        title: 'Centralized Protection & Control (CPC)',
        subtitle: 'Virtualizing the Relay Hall',
        icon: Server,
        color: 'blue',
        concept: "Moving protection algorithms from dedicated hardware boxes to a high-performance central server (Substation PC) using Software-Defined Networking.",
        techSpecs: [
            { label: "Protocol", value: "IEC 61850-9-2 (Process Bus)" },
            { label: "OS Requirement", value: "Hard Real-Time (RTOS)" },
            { label: "Redundancy", value: "PRP / HSR (Zero Recovery Time)" }
        ],
        content: [
            "Architecture: Merging Units (MUs) digitize CT/VT signals at the source. Fiber carries Sampled Values (SV) to the control room.",
            "Benefit: Hardware independence. Upgrade protection schemes by updating software containers (e.g., Docker) without touching a screwdriver.",
            "Engineering Challenge: Deterministic processing. The server must guarantee the trip command is issued within 3-4ms of the fault, regardless of CPU load."
        ]
    },
    {
        id: 'twfl',
        category: 'Physics',
        title: 'Traveling Wave Fault Location',
        subtitle: 'From Impedance to Time-of-Flight',
        icon: Activity,
        color: 'purple',
        concept: "Using the high-frequency voltage transients (MHz) generated by a fault to pinpoint location with meter-level accuracy.",
        techSpecs: [
            { label: "Sampling Rate", value: "1 MHz - 10 MHz" },
            { label: "Accuracy", value: "+/- 1 Tower Span" },
            { label: "Physics", value: "d = (v × Δt) / 2" }
        ],
        content: [
            "Traditional Method: Impedance (Z = V/I). Error margin ~5-10% due to CT errors and line sag.",
            "New Method: When a fault occurs, a surge wave travels close to the speed of light (c) towards both line ends. By timestamping the arrival at both terminals using GPS-synced clocks (PTP), we calculate distance based on time difference.",
            "Requirement: High-bandwidth transducers and relays capable of 'Point-on-Wave' sampling."
        ]
    },
    {
        id: 'gfm',
        category: 'Renewables',
        title: 'Grid-Forming Inverters (GFM)',
        subtitle: 'Synthetic Inertia for Stability',
        icon: Zap,
        color: 'amber',
        concept: "Inverters that behave like voltage sources, actively resisting frequency changes (RoCoF) rather than just following the grid sine wave.",
        techSpecs: [
            { label: "Control Mode", value: "Voltage Source (VSM)" },
            { label: "Fault Current", value: "Low (1.2 - 1.5 pu)" },
            { label: "Response", value: "Sub-cycle (<20ms)" }
        ],
        content: [
            "Problem: Solar/Wind are 'Grid Following'. They inject current into the grid frequency. If grid inertia drops (less rotating mass), frequency collapses fast during faults.",
            "Solution: GFM inverters simulate mass. If frequency dips, they instantly inject active power from battery reserves.",
            "Protection Impact: GFM limits fault current to protect electronics. Traditional overcurrent relays (50/51) may NOT see enough current to trip. We need Distance (21) or Differential (87) protection."
        ]
    },
    {
        id: 'goose_sec',
        category: 'Cybersecurity',
        title: 'Secure GOOSE (IEC 62351)',
        subtitle: 'Authenticating the Trip Signal',
        icon: Shield,
        color: 'red',
        concept: "Adding cryptographic signatures to protection messages to prevent 'Replay Attacks' or 'Man-in-the-Middle' injection of false trips.",
        techSpecs: [
            { label: "Standard", value: "IEC 62351-6" },
            { label: "Algorithm", value: "HMAC-SHA256" },
            { label: "Key Mgmt", value: "GDOI (Group Domain)" }
        ],
        content: [
            "Vulnerability: Standard GOOSE is unencrypted for speed. An attacker inside the substation LAN can inject a raw Ethernet frame pretending to be a relay.",
            "The Fix: Append an Authentication Tag (HMAC) to the frame. The receiver verifies the tag before tripping.",
            "Constraint: Crypto takes time. Hardware acceleration (FPGA/ASIC) is mandatory to keep total processing time under 4ms."
        ]
    },
    {
        id: 'sv_sync',
        category: 'Process Bus',
        title: 'Sampled Values & PTP Sync',
        subtitle: 'The Heartbeat of Digital Substations',
        icon: Clock,
        color: 'cyan',
        concept: "Replacing 1A/110V copper wires with a multicast stream of digitized measurements (IEC 61850-9-2).",
        techSpecs: [
            { label: "Rate (50Hz)", value: "4000 / 4800 Hz" },
            { label: "Sync Protocol", value: "IEEE 1588 v2 (PTP)" },
            { label: "Max Drift", value: "< 1 µs" }
        ],
        content: [
            "Mechanism: Merging Units publish current/voltage samples 80 times per cycle.",
            "Criticality: Differential protection relies on comparing these samples. If clocks drift by even 1ms, it creates a phase shift error (18° @ 50Hz), causing a false trip.",
            "Design Rule: The 'Grandmaster Clock' is the single point of failure. Redundant GNSS clocks are mandatory."
        ]
    },
    {
        id: 'digital_twin',
        category: 'Maintenance',
        title: 'Breaker Signature Analysis',
        subtitle: 'Predictive Condition Monitoring',
        icon: Layers,
        color: 'green',
        concept: "Using high-speed sampling of the Trip Coil current profile to diagnose mechanical health before failure.",
        techSpecs: [
            { label: "Signature", value: "Coil Current Waveform" },
            { label: "Detection", value: "Stuck Latch / Friction" },
            { label: "Strategy", value: "CBM (Condition Based)" }
        ],
        content: [
            "Physics: When a trip coil energizes, the plunger movement creates a specific dip in the current curve (back-EMF).",
            "Diagnosis: If the dip arrives later than the baseline 'Golden Signature', mechanism friction is high.",
            "Outcome: Maintain the breaker *before* it gets stuck, rather than relying on a 'Breaker Failure' operation during a fault."
        ]
    }
];

const SmartGridTrends = () => {
    return (
        <div className="space-y-8 animate-fade-in max-w-7xl mx-auto pb-12">
            
            {/* Header */}
            <div className="bg-slate-900 rounded-3xl p-8 md:p-12 overflow-hidden shadow-2xl border border-slate-800 relative">
                <div className="absolute top-0 right-0 p-12 opacity-10">
                    <Cpu className="w-64 h-64 text-blue-500" />
                </div>
                <div className="relative z-10">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/20 text-blue-300 text-xs font-bold uppercase tracking-widest mb-4 border border-blue-500/30">
                        <BookOpen className="w-3 h-3" /> Advanced Engineering Concepts
                    </div>
                    <h1 className="text-4xl md:text-5xl font-black text-white mb-6 leading-tight">
                        Future Grid Intelligence
                    </h1>
                    <p className="text-lg text-slate-400 max-w-3xl leading-relaxed">
                        Beyond the standards. A deep dive into the physics, logic, and architecture defining the next generation of Protection & Control systems. 
                        These modules bridge the gap between theory and the digital substation reality.
                    </p>
                </div>
            </div>

            {/* Insight Cards */}
            <div className="grid grid-cols-1 gap-8">
                {INSIGHTS.map((item) => (
                    <div key={item.id} className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-sm hover:shadow-lg transition-shadow">
                        <div className="grid grid-cols-1 lg:grid-cols-12">
                            
                            {/* Left: Header & Concept */}
                            <div className="lg:col-span-4 p-8 bg-slate-50 dark:bg-slate-950 border-b lg:border-b-0 lg:border-r border-slate-200 dark:border-slate-800 flex flex-col justify-between">
                                <div>
                                    <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-lg bg-${item.color}-100 dark:bg-${item.color}-900/30 text-${item.color}-700 dark:text-${item.color}-300 text-xs font-bold uppercase mb-4`}>
                                        <item.icon className="w-3 h-3" /> {item.category}
                                    </div>
                                    <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-2">{item.title}</h3>
                                    <p className="text-sm text-slate-500 font-medium mb-6">{item.subtitle}</p>
                                    <div className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed italic border-l-4 border-slate-200 dark:border-slate-800 pl-4">
                                        "{item.concept}"
                                    </div>
                                </div>
                                <div className="mt-8 pt-6 border-t border-slate-200 dark:border-slate-800">
                                    <div className="text-[10px] font-bold text-slate-400 uppercase mb-3">Key Specifications</div>
                                    <div className="space-y-2">
                                        {item.techSpecs.map((spec, i) => (
                                            <div key={i} className="flex justify-between text-xs">
                                                <span className="text-slate-500">{spec.label}</span>
                                                <span className="font-mono font-bold text-slate-700 dark:text-slate-300">{spec.value}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>

                            {/* Right: Detailed Content */}
                            <div className="lg:col-span-8 p-8">
                                <h4 className="text-sm font-bold text-slate-900 dark:text-white uppercase mb-4 flex items-center gap-2">
                                    <FileCode className="w-4 h-4 text-blue-500" /> Technical Breakdown
                                </h4>
                                <div className="space-y-6">
                                    {item.content.map((paragraph, i) => (
                                        <div key={i} className="flex gap-4">
                                            <div className="mt-1 shrink-0">
                                                <CheckCircle2 className="w-5 h-5 text-slate-400" />
                                            </div>
                                            <p className="text-slate-600 dark:text-slate-300 text-sm leading-relaxed">
                                                {paragraph.split(':').length > 1 ? (
                                                    <>
                                                        <strong className="text-slate-900 dark:text-white">{paragraph.split(':')[0]}:</strong>
                                                        {paragraph.split(':').slice(1).join(':')}
                                                    </>
                                                ) : paragraph}
                                            </p>
                                        </div>
                                    ))}
                                </div>

                                <div className="mt-8 p-4 bg-blue-50 dark:bg-blue-900/10 rounded-xl border border-blue-100 dark:border-blue-900/30 flex items-start gap-3">
                                    <Activity className="w-5 h-5 text-blue-600 dark:text-blue-400 shrink-0 mt-0.5" />
                                    <div>
                                        <h5 className="font-bold text-blue-700 dark:text-blue-300 text-sm">Engineer's Takeaway</h5>
                                        <p className="text-xs text-blue-600 dark:text-blue-200 mt-1 leading-relaxed">
                                            Understanding this technology shifts the focus from "how to wire it" to "how to configure the data flow". 
                                            The physics remain the same (Ohm's Law, Kirchhoff), but the medium has changed from copper to light.
                                        </p>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                ))}
            </div>

            {/* Footer Note */}
            <div className="text-center py-8">
                <p className="text-sm text-slate-500">
                    Content based on IEEE PSRC Working Group reports and CIGRE Technical Brochures (B5 Study Committee).
                </p>
            </div>

        </div>
    );
};

export default SmartGridTrends;
